CREATE TABLE `training_jobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`name` varchar(256) NOT NULL,
	`description` text,
	`baseModel` varchar(256) NOT NULL,
	`modelPath` varchar(512),
	`outputPath` varchar(512),
	`trainingType` enum('sft','lora','qlora','full') NOT NULL DEFAULT 'lora',
	`datasetPath` varchar(512) NOT NULL,
	`epochs` int NOT NULL DEFAULT 3,
	`batchSize` int NOT NULL DEFAULT 4,
	`learningRate` varchar(32) DEFAULT '2e-5',
	`maxSeqLength` int DEFAULT 2048,
	`gradientAccumulation` int DEFAULT 1,
	`warmupSteps` int DEFAULT 100,
	`loraRank` int DEFAULT 16,
	`loraAlpha` int DEFAULT 32,
	`loraDropout` varchar(16) DEFAULT '0.05',
	`hostId` varchar(32) NOT NULL,
	`gpuCount` int NOT NULL DEFAULT 1,
	`status` enum('queued','preparing','running','completed','failed','cancelled') NOT NULL DEFAULT 'queued',
	`progress` int DEFAULT 0,
	`currentEpoch` int DEFAULT 0,
	`currentStep` int DEFAULT 0,
	`totalSteps` int DEFAULT 0,
	`trainLoss` varchar(32),
	`evalLoss` varchar(32),
	`startedAt` timestamp,
	`completedAt` timestamp,
	`estimatedTimeRemaining` int,
	`errorMessage` text,
	`logPath` varchar(512),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `training_jobs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `training_jobs` ADD CONSTRAINT `training_jobs_userId_users_id_fk` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;